services:
  flux-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flux-img2img-api
    restart: unless-stopped
    runtime: nvidia
    
    # GPU configuration - use GPU 7
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility]
    
    # Environment variables
    environment:
      - CUDA_VISIBLE_DEVICES=7
      - FP4_API_PORT=${FP4_API_PORT:-9001}
      - NVIDIA_VISIBLE_DEVICES=7
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    
    # Port mapping
    ports:
      - "${FP4_API_PORT:-9001}:${FP4_API_PORT:-9001}"
    
    # Override command if needed (optional)
    # command: ["./start_flux_api.sh"]  # Uncomment to use start_flux_api.sh instead
    # command: ["/bin/bash"]            # Uncomment to get bash shell
    # command: ["python3", "main.py"]   # Uncomment to run main.py directly
    
    # Volume mounts for persistent data
    volumes:
      - ./generated_images:/app/generated_images
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - /data/tianyu/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/torch:/root/.cache/torch
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (adjust based on your system)
    # mem_limit: 32g
    # memswap_limit: 32g
    
    # Security options
    security_opt:
      - seccomp:unconfined
    
    # Shared memory for PyTorch
    shm_size: 2g

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: flux-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - flux-api
    profiles:
      - production

# Networks
networks:
  default:
    name: flux-network
    driver: bridge

# Volumes for persistent data
volumes:
  huggingface_cache:
    driver: local
  torch_cache:
    driver: local
  generated_images:
    driver: local
  logs:
    driver: local
