name: img2img
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - accelerate==1.10.1
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiohttp_socks==0.10.1
    - aiosignal==1.4.0
    - albucore==0.0.24
    - albumentations==2.0.8
    - alembic==1.16.4
    - annotated-types==0.7.0
    - anyio==4.10.0
    - arrow==1.3.0
    - attrs==25.3.0
    - av==15.0.0
    - binaryornot==0.4.4
    - black==25.1.0
    - certifi==2025.8.3
    - cffi==1.17.1
    - chardet==5.2.0
    - charset-normalizer==3.4.3
    - click==8.1.8
    - coloredlogs==15.0.1
    - comfy-cli==1.5.0
    - comfyui-embedded-docs==0.2.6
    - comfyui_frontend_package==1.25.10
    - comfyui_workflow_templates==0.1.65
    - contourpy==1.3.3
    - cookiecutter==2.6.0
    - cryptography==45.0.6
    - cycler==0.12.1
    - Cython==3.1.3
    - diffusers==0.35.1
    - easydict==1.13
    - einops==0.8.1
    - facexlib==0.3.0
    - fastapi==0.116.1
    - filelock==3.19.1
    - filterpy==1.4.5
    - fire==0.7.1
    - flatbuffers==25.2.10
    - fonttools==4.59.2
    - frozenlist==1.7.0
    - fsspec==2025.7.0
    - gitdb==4.0.12
    - GitPython==3.1.45
    - greenlet==3.2.4
    - h11==0.16.0
    - h2==4.3.0
    - hf-xet==1.1.9
    - hpack==4.1.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.34.4
    - humanfriendly==10.0
    - hyperframe==6.1.0
    - idna==3.10
    - imageio==2.37.0
    - importlib_metadata==8.7.0
    - insightface==0.7.3
    - isort==6.0.1
    - Jinja2==3.1.6
    - joblib==1.5.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.4.1
    - kiwisolver==1.4.9
    - kornia==0.8.1
    - kornia_rs==0.1.9
    - lazy_loader==0.4
    - llvmlite==0.44.0
    - loguru==0.7.3
    - Mako==1.3.10
    - markdown-it-py==4.0.0
    - MarkupSafe==3.0.2
    - matrix-nio==0.25.2
    - mdurl==0.1.2
    - mixpanel==4.10.1
    - ml_dtypes==0.5.3
    - mpmath==1.3.0
    - multidict==6.6.4
    - mypy_extensions==1.1.0
    - networkx==3.5
    - numba==0.61.2
    - onnx==1.19.0
    - onnxruntime==1.22.1
    - onnxruntime-gpu==1.22.0
    - opencv-python==4.12.0.88
    - opencv-python-headless==4.12.0.88
    - packaging==25.0
    - pathspec==0.12.1
    - platformdirs==4.3.8
    - pooch==1.8.2
    - prettytable==3.16.0
    - prompt_toolkit==3.0.51
    - propcache==0.3.2
    - protobuf==6.32.0
    - psutil==7.0.0
    - pycparser==2.22
    - pycryptodome==3.23.0
    - pydantic==2.11.7
    - pydantic-settings==2.10.1
    - pydantic_core==2.33.2
    - PyGithub==2.7.0
    - Pygments==2.19.2
    - PyJWT==2.10.1
    - PyMatting==1.1.14
    - PyNaCl==1.5.0
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.1
    - python-multipart==0.0.20
    - python-slugify==8.0.4
    - python-socks==2.7.2
    - questionary==2.1.0
    - referencing==0.36.2
    - regex==2025.7.34
    - rembg==2.0.67
    - rich==14.1.0
    - rpds-py==0.27.0
    - ruff==0.12.10
    - safetensors==0.6.2
    - semver==3.0.4
    - sentencepiece==0.2.1
    - setuptools==78.1.1
    - shellingham==1.5.4
    - simsimd==6.5.1
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - soundfile==0.13.1
    - spandrel==0.4.1
    - SQLAlchemy==2.0.43
    - starlette==0.47.3
    - stringzilla==3.12.6
    - sympy==1.14.0
    - termcolor==3.1.0
    - text-unidecode==1.3
    - threadpoolctl==3.6.0
    - tifffile==2025.8.28
    - timm==1.0.19
    - tokenizers==0.21.4
    - toml==0.10.2
    - tomlkit==0.13.3
    - torchsde==0.2.6
    - triton==3.4.0
    - typer==0.16.1
    - types-python-dateutil==2.9.0.20250822
    - typing-inspection==0.4.1
    - typing_extensions==4.14.1
    - unpaddedbase64==2.1.0
    - urllib3==2.5.0
    - uv==0.8.13
    - uvicorn==0.35.0
    - wcwidth==0.2.13
    - websocket-client==1.8.0
    - wheel==0.45.1
    - yarl==1.20.1
    - zipp==3.23.0
    - loguru==0.7.3
